all : client
client :
	g++ -o client_step1 client_step1.cpp
	g++ -o client_step2 client_step2.cpp
	g++ -o client_step3 client_step3.cpp
	g++ -o client_step4 client_step4.cpp
	g++ -o client_step5 client_step5.cpp
	g++ -o client_step6 client_step6.cpp
	
clean : 
	rm client_step1 
	rm client_step2 
	rm client_step3
	rm client_step4
	rm client_step5
	rm client_step6 
