all : server
server :
	g++ -o server_step1 server_step1.cpp
	g++ -o server_step2 server_step2.cpp
	g++ -o server_step3 server_step3.cpp
	g++ -o server_step4 server_step4.cpp
	g++ -o server_step5 server_step5.cpp
	g++ -o server_step6 server_step6.cpp
	
clean : 
	rm server_step1 
	rm server_step2 
	rm server_step3
	rm server_step4
	rm server_step5
	rm server_step6 
